/**:
  ros__parameters:
    camera_frame: "daheng_cam" # default
    camera_topic: "daheng/image" # default

    fps: 60
    exposure: 10000.0
    gain: 20.0
    width: 640
    height: 480

    brightness: 150 # -150~150
    contrast: 100 # -50~100
    sharpness: 0.5 # 0.1~5.0

    # uncomment the following with your parameters to publish undistorted image
    # K: [329.99606496,   0.,         320.80941048,  0.,  330.26956203, 256.47746577, 0.,           0.,           1.        ]
    # D: [-0.34437734,  0.14404286, -0.00051884, -0.00059654, -0.02975557]
